{
 "title": "Kafka",
 "description": "Kafka related metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(application_ready_time_seconds, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Message rate",
   "type": "timeseries",
   "description": "Mean message rate per Kafka topic",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_BrokerTopicMetrics_OneMinuteRate{namespace=\"$environment\", name=\"MessagesInPerSec\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming bytes",
   "type": "timeseries",
   "description": "Incoming bytes per Kafka broker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (kafka_server_socket_server_metrics_incoming_byte_rate{namespace=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing bytes",
   "type": "timeseries",
   "description": "Outgoing bytes per Kafka broker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (kafka_server_socket_server_metrics_outgoing_byte_rate{namespace=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka produce rate",
   "type": "timeseries",
   "description": "Kafka produce rate per container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(container) (kafka_producer_request_rate{namespace=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka consume rate",
   "type": "timeseries",
   "description": "Kafka consume rate per container",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(container) (kafka_consumer_fetch_manager_fetch_rate{namespace=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka topic error rate",
   "type": "timeseries",
   "description": "Kafka error rate per topic and container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kafka_producer_topic_record_error_rate{namespace=\"$environment\"}",
     "legendFormat": "{{container}}-{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka topic lag",
   "type": "timeseries",
   "description": "Lag of Kafka topics per container",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(container, topic) (kafka_consumer_fetch_manager_records_lag_avg{namespace=\"$environment\"})",
     "legendFormat": "{{container}}-{{topic}}"
    }
   ]
  }
 ]
}