{
 "title": "ONIEUW EPD",
 "description": "EPD related metrics",
 "tags": [ "ONIEUW" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(application_ready_time_seconds{namespace=onieuw}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage per container",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(container) (system_load_average_1m{namespace=\"onieuw\", container=~\"$container\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Memory usage per container",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(container) (jvm_memory_committed_bytes{namespace=\"onieuw\", container=~\"$container\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Active DB connections",
   "type": "timeseries",
   "description": "Active DB connections per container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{namespace=\"onieuw\", container=~\"$container\"}",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "jdbc_connections_active{namespace=\"onieuw\", container=~\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Tomcat sessions",
   "type": "timeseries",
   "description": "Active Tomcat sessions per container",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions{namespace=\"onieuw\", container=~\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Log messages",
   "type": "timeseries",
   "description": "Rate of log messages(all levels) per pod",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(container) (rate(logback_events_total{namespace=\"onieuw\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live threads",
   "type": "timeseries",
   "description": "Live threads per pod",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=\"onieuw\", container=~\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}