{
 "title": "Artemis onieuw",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "address",
    "query": {
     "query": "label_values(artemis_address_size{namespace=onieuw}, address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Connection count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "artemis_connection_count{namespace=\"onieuw\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Address size",
   "type": "timeseries",
   "description": "Address size",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(address) (artemis_address_size{namespace=\"onieuw\", address=~\"$address\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "timeseries",
   "description": "Consumer count per address",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(address) (artemis_consumer_count{namespace=\"onieuw\", address=~\"$address\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Acknowledge attempts",
   "type": "timeseries",
   "description": "Acknowledge attempts per address",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(address) (artemis_acknowledge_attempts{namespace=\"onieuw\", address=~\"$address\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Killed messages",
   "type": "timeseries",
   "description": "Killed messages per address",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(address) (artemis_messages_killed{namespace=\"onieuw\", address=~\"$address\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expired messages",
   "type": "timeseries",
   "description": "Expired messages per address",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(address) (artemis_messages_expired{namespace=\"onieuw\", address=~\"$address\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}