{
 "title": "Nodes stats",
 "tags": [ "node-exporter" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Quick system info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "description": "Average cpu usage of the nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * avg (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory free",
   "type": "gauge",
   "description": "Average memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(sum(node_memory_MemAvailable_bytes)) / avg(sum(node_memory_MemTotal_bytes))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load",
   "type": "gauge",
   "description": "Average system load",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(node_load1)) / avg(count(node_cpu_seconds_total{mode=\"system\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "gauge",
   "description": "Average free space",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(sum(node_filesystem_free_bytes{mountpoint=\"/\"})) by (mountpoint) / avg(sum(node_filesystem_size_bytes{mountpoint=\"/\"})) by (mountpoint)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Detailed system info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Cpu usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "barchart",
   "description": "Memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemFree_bytes{instance=~\"$instance\"} - node_memory_Buffers_bytes{instance=~\"$instance\"} - node_memory_Cached_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Used memory"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Free"
    }
   ]
  }
 ]
}