apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - helm-repo.yaml
  - prometheus-helm-release.yaml
  - grafana-helm-release.yaml
  - sa.yaml
  - sample_dashboard/grafana-dashboardNodes.yaml
