{
 "title": "Cluster Overview Details",
 "description": "Summary metrics about kubernetes cluster",
 "tags": [
  "details",
  "kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Containers for namespace(s): $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers Running",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{namespace=~\"$namespace\"} == 1",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting{namespace=~\"$namespace\"} == 1",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated{namespace=~\"$namespace\"} == 1",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Containers Restart Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods for namespace(s): $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods Running",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"} == 1",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"} == 1",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"} == 1",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"} == 1",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"} == 1",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pods Restart Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (kube_pod_container_status_restarts_total{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Pods",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"cpu\"} * on (namespace, pod) group_left() kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requested By Pods",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"memory\"} * on (namespace, pod) group_left() kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployments for namespace(s): $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs for namespace(s): $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_job_status_active{namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Succeeded Jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_job_status_succeeded{namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_job_status_failed{namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cluster Pod Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_info) / sum(kube_node_status_allocatable{resource=\"pods\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 9, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(kube_node_status_allocatable{resource=\"cpu\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster Pod Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"pods\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"pods\"})",
       "legendFormat": "capacity"
      },
      { "expr": "sum(kube_pod_info)", "legendFormat": "requested" }
     ]
    },
    {
     "title": "Cluster CPU Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
       "legendFormat": "limited"
      }
     ]
    },
    {
     "title": "Cluster Mem Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})",
       "legendFormat": "limited"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number Of Nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "sum(kube_node_info)" }
     ]
    },
    {
     "title": "Nodes Out of Disk",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable)"
      }
     ]
    }
   ]
  }
 ]
}