---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: service-b
  labels:
    app: kafka
spec:
  ports:
    - port: 19092
      name: kafka-internal
  selector:
    app: kafka
---
