apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: service-b
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-service
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5556"
    spec:
      containers:
        - name: kafka-broker
          image: "confluentinc/cp-kafka:7.3.0"
          ports:
            - containerPort: 19092
              name: kafka-internal
            - containerPort: 5555
              name: jmx
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_OPTS
              value: "-Dlogging.level=INFO"
            - name: KAFKA_HEAP_OPTS
              value: "-Xms512M -Xmx512M"
            - name: KAFKA_LOG_DIRS
              value: "/home/appuser/kafka/data/logs"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181.zookeeper"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:19092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_JMX_PORT
              value: "5555"
          # This is required because the Downward API does not yet support identification of
          # pod numbering in statefulsets. Thus, we are required to specify a command which
          # allows us to extract the pod ID for usage as the Kafka Broker ID.
          # See: https://github.com/kubernetes/kubernetes/issues/31218
          command:
            - sh
            - -exc
            - |
              export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
              export KAFKA_ADVERTISED_LISTENERS=INTERNAL://${POD_NAME}.kafka-service:19092 && \
              exec /etc/confluent/docker/run
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - "/bin/kafka-broker-api-versions --bootstrap-server=localhost:19092"
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "/bin/kafka-broker-api-versions --bootstrap-server=localhost:19092"
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          volumeMounts:
            - name: datadir-0
              mountPath: /home/appuser/kafka/data
      volumes:
        - name: datadir-0
          emptyDir: {}
